version: "3"
services:
  mongo:
    image: 'mongo:3.4.20-xenial'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'


  powerrank:
    restart: always
    depends_on:
      - 'mongo'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/powerrank
      - __API_BASE_URL__="/api"
      - NODE_ENV="production"
    build:
      context: .
    ports:
      - "5000:80"
    networks:
      # - reverseproxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=powerrank"
      - "traefik.frontend.rule=Host:powerrank.io,powerrank.pc.codes"
      - "traefik.docker.network=traefik_reverseproxy"

# networks:
#   reverseproxy:
#     external:
#       name: traefik_reverseproxy

volumes:
  mongo:
